/*
 * Copyright (C) 2019 The Turms Project
 * https://github.com/turms-im/turms
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/message/query_pending_messages_with_total_request.proto

package im.turms.common.model.dto.request.message;

public interface QueryPendingMessagesWithTotalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.QueryPendingMessagesWithTotalRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return Whether the size field is set.
   */
  boolean hasSize();
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   * @return The size.
   */
  com.google.protobuf.Int32Value getSize();
  /**
   * <code>.google.protobuf.Int32Value size = 1;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getSizeOrBuilder();
}
