/*
 * Copyright (C) 2019 The Turms Project
 * https://github.com/turms-im/turms
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/message/message_statuses.proto

package im.turms.common.model.bo.message;

/**
 * Protobuf type {@code im.turms.proto.MessageStatuses}
 */
public  final class MessageStatuses extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:im.turms.proto.MessageStatuses)
    MessageStatusesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageStatuses.newBuilder() to construct.
  private MessageStatuses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageStatuses() {
    messageStatuses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageStatuses();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageStatuses(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              messageStatuses_ = new java.util.ArrayList<MessageStatus>();
              mutable_bitField0_ |= 0x00000001;
            }
            messageStatuses_.add(
                input.readMessage(MessageStatus.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        messageStatuses_ = java.util.Collections.unmodifiableList(messageStatuses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageStatusesOuterClass.internal_static_im_turms_proto_MessageStatuses_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageStatusesOuterClass.internal_static_im_turms_proto_MessageStatuses_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MessageStatuses.class, MessageStatuses.Builder.class);
  }

  public static final int MESSAGE_STATUSES_FIELD_NUMBER = 1;
  private java.util.List<MessageStatus> messageStatuses_;
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  public java.util.List<MessageStatus> getMessageStatusesList() {
    return messageStatuses_;
  }
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  public java.util.List<? extends MessageStatusOrBuilder>
      getMessageStatusesOrBuilderList() {
    return messageStatuses_;
  }
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  public int getMessageStatusesCount() {
    return messageStatuses_.size();
  }
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  public MessageStatus getMessageStatuses(int index) {
    return messageStatuses_.get(index);
  }
  /**
   * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
   */
  public MessageStatusOrBuilder getMessageStatusesOrBuilder(
      int index) {
    return messageStatuses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messageStatuses_.size(); i++) {
      output.writeMessage(1, messageStatuses_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < messageStatuses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, messageStatuses_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MessageStatuses)) {
      return super.equals(obj);
    }
    MessageStatuses other = (MessageStatuses) obj;

    if (!getMessageStatusesList()
        .equals(other.getMessageStatusesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessageStatusesCount() > 0) {
      hash = (37 * hash) + MESSAGE_STATUSES_FIELD_NUMBER;
      hash = (53 * hash) + getMessageStatusesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MessageStatuses parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageStatuses parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageStatuses parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageStatuses parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageStatuses parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageStatuses parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageStatuses parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageStatuses parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageStatuses parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MessageStatuses parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageStatuses parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageStatuses parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MessageStatuses prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.turms.proto.MessageStatuses}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:im.turms.proto.MessageStatuses)
          MessageStatusesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageStatusesOuterClass.internal_static_im_turms_proto_MessageStatuses_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageStatusesOuterClass.internal_static_im_turms_proto_MessageStatuses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageStatuses.class, MessageStatuses.Builder.class);
    }

    // Construct using im.turms.common.model.bo.message.MessageStatuses.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageStatusesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (messageStatusesBuilder_ == null) {
        messageStatuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        messageStatusesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageStatusesOuterClass.internal_static_im_turms_proto_MessageStatuses_descriptor;
    }

    @java.lang.Override
    public MessageStatuses getDefaultInstanceForType() {
      return MessageStatuses.getDefaultInstance();
    }

    @java.lang.Override
    public MessageStatuses build() {
      MessageStatuses result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public MessageStatuses buildPartial() {
      MessageStatuses result = new MessageStatuses(this);
      int from_bitField0_ = bitField0_;
      if (messageStatusesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messageStatuses_ = java.util.Collections.unmodifiableList(messageStatuses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messageStatuses_ = messageStatuses_;
      } else {
        result.messageStatuses_ = messageStatusesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MessageStatuses) {
        return mergeFrom((MessageStatuses)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MessageStatuses other) {
      if (other == MessageStatuses.getDefaultInstance()) return this;
      if (messageStatusesBuilder_ == null) {
        if (!other.messageStatuses_.isEmpty()) {
          if (messageStatuses_.isEmpty()) {
            messageStatuses_ = other.messageStatuses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageStatusesIsMutable();
            messageStatuses_.addAll(other.messageStatuses_);
          }
          onChanged();
        }
      } else {
        if (!other.messageStatuses_.isEmpty()) {
          if (messageStatusesBuilder_.isEmpty()) {
            messageStatusesBuilder_.dispose();
            messageStatusesBuilder_ = null;
            messageStatuses_ = other.messageStatuses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messageStatusesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMessageStatusesFieldBuilder() : null;
          } else {
            messageStatusesBuilder_.addAllMessages(other.messageStatuses_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MessageStatuses parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MessageStatuses) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<MessageStatus> messageStatuses_ =
      java.util.Collections.emptyList();
    private void ensureMessageStatusesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messageStatuses_ = new java.util.ArrayList<MessageStatus>(messageStatuses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            MessageStatus, MessageStatus.Builder, MessageStatusOrBuilder> messageStatusesBuilder_;

    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public java.util.List<MessageStatus> getMessageStatusesList() {
      if (messageStatusesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messageStatuses_);
      } else {
        return messageStatusesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public int getMessageStatusesCount() {
      if (messageStatusesBuilder_ == null) {
        return messageStatuses_.size();
      } else {
        return messageStatusesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public MessageStatus getMessageStatuses(int index) {
      if (messageStatusesBuilder_ == null) {
        return messageStatuses_.get(index);
      } else {
        return messageStatusesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder setMessageStatuses(
        int index, MessageStatus value) {
      if (messageStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageStatusesIsMutable();
        messageStatuses_.set(index, value);
        onChanged();
      } else {
        messageStatusesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder setMessageStatuses(
        int index, MessageStatus.Builder builderForValue) {
      if (messageStatusesBuilder_ == null) {
        ensureMessageStatusesIsMutable();
        messageStatuses_.set(index, builderForValue.build());
        onChanged();
      } else {
        messageStatusesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder addMessageStatuses(MessageStatus value) {
      if (messageStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageStatusesIsMutable();
        messageStatuses_.add(value);
        onChanged();
      } else {
        messageStatusesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder addMessageStatuses(
        int index, MessageStatus value) {
      if (messageStatusesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessageStatusesIsMutable();
        messageStatuses_.add(index, value);
        onChanged();
      } else {
        messageStatusesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder addMessageStatuses(
        MessageStatus.Builder builderForValue) {
      if (messageStatusesBuilder_ == null) {
        ensureMessageStatusesIsMutable();
        messageStatuses_.add(builderForValue.build());
        onChanged();
      } else {
        messageStatusesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder addMessageStatuses(
        int index, MessageStatus.Builder builderForValue) {
      if (messageStatusesBuilder_ == null) {
        ensureMessageStatusesIsMutable();
        messageStatuses_.add(index, builderForValue.build());
        onChanged();
      } else {
        messageStatusesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder addAllMessageStatuses(
        java.lang.Iterable<? extends MessageStatus> values) {
      if (messageStatusesBuilder_ == null) {
        ensureMessageStatusesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageStatuses_);
        onChanged();
      } else {
        messageStatusesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder clearMessageStatuses() {
      if (messageStatusesBuilder_ == null) {
        messageStatuses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messageStatusesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public Builder removeMessageStatuses(int index) {
      if (messageStatusesBuilder_ == null) {
        ensureMessageStatusesIsMutable();
        messageStatuses_.remove(index);
        onChanged();
      } else {
        messageStatusesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public MessageStatus.Builder getMessageStatusesBuilder(
        int index) {
      return getMessageStatusesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public MessageStatusOrBuilder getMessageStatusesOrBuilder(
        int index) {
      if (messageStatusesBuilder_ == null) {
        return messageStatuses_.get(index);  } else {
        return messageStatusesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public java.util.List<? extends MessageStatusOrBuilder>
         getMessageStatusesOrBuilderList() {
      if (messageStatusesBuilder_ != null) {
        return messageStatusesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messageStatuses_);
      }
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public MessageStatus.Builder addMessageStatusesBuilder() {
      return getMessageStatusesFieldBuilder().addBuilder(
          MessageStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public MessageStatus.Builder addMessageStatusesBuilder(
        int index) {
      return getMessageStatusesFieldBuilder().addBuilder(
          index, MessageStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .im.turms.proto.MessageStatus message_statuses = 1;</code>
     */
    public java.util.List<MessageStatus.Builder>
         getMessageStatusesBuilderList() {
      return getMessageStatusesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            MessageStatus, MessageStatus.Builder, MessageStatusOrBuilder>
        getMessageStatusesFieldBuilder() {
      if (messageStatusesBuilder_ == null) {
        messageStatusesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                MessageStatus, MessageStatus.Builder, MessageStatusOrBuilder>(
                messageStatuses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messageStatuses_ = null;
      }
      return messageStatusesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:im.turms.proto.MessageStatuses)
  }

  // @@protoc_insertion_point(class_scope:im.turms.proto.MessageStatuses)
  private static final MessageStatuses DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MessageStatuses();
  }

  public static MessageStatuses getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageStatuses>
      PARSER = new com.google.protobuf.AbstractParser<MessageStatuses>() {
    @java.lang.Override
    public MessageStatuses parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageStatuses(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageStatuses> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageStatuses> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public MessageStatuses getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

