/*
 * Copyright (C) 2019 The Turms Project
 * https://github.com/turms-im/turms
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/signal/ack_request.proto

package im.turms.common.model.dto.request.signal;

public interface AckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:im.turms.proto.AckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 message_ids = 1;</code>
   * @return A list containing the messageIds.
   */
  java.util.List<java.lang.Long> getMessageIdsList();
  /**
   * <code>repeated int64 message_ids = 1;</code>
   * @return The count of messageIds.
   */
  int getMessageIdsCount();
  /**
   * <code>repeated int64 message_ids = 1;</code>
   * @param index The index of the element to return.
   * @return The messageIds at the given index.
   */
  long getMessageIds(int index);
}
