/*
 * Copyright (C) 2019 The Turms Project
 * https://github.com/turms-im/turms
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: constant/message_delivery_status.proto

package im.turms.common.constant;

/**
 * Protobuf enum {@code im.turms.proto.MessageDeliveryStatus}
 */
public enum MessageDeliveryStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>READY = 0;</code>
   */
  READY(0),
  /**
   * <code>SENDING = 1;</code>
   */
  SENDING(1),
  /**
   * <code>RECEIVED = 2;</code>
   */
  RECEIVED(2),
  /**
   * <code>RECALLING = 3;</code>
   */
  RECALLING(3),
  /**
   * <code>RECALLED = 4;</code>
   */
  RECALLED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>READY = 0;</code>
   */
  public static final int READY_VALUE = 0;
  /**
   * <code>SENDING = 1;</code>
   */
  public static final int SENDING_VALUE = 1;
  /**
   * <code>RECEIVED = 2;</code>
   */
  public static final int RECEIVED_VALUE = 2;
  /**
   * <code>RECALLING = 3;</code>
   */
  public static final int RECALLING_VALUE = 3;
  /**
   * <code>RECALLED = 4;</code>
   */
  public static final int RECALLED_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageDeliveryStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageDeliveryStatus forNumber(int value) {
    switch (value) {
      case 0: return READY;
      case 1: return SENDING;
      case 2: return RECEIVED;
      case 3: return RECALLING;
      case 4: return RECALLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageDeliveryStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageDeliveryStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageDeliveryStatus>() {
          public MessageDeliveryStatus findValueByNumber(int number) {
            return MessageDeliveryStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return MessageDeliveryStatusOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageDeliveryStatus[] VALUES = values();

  public static MessageDeliveryStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageDeliveryStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:im.turms.proto.MessageDeliveryStatus)
}

